name: Node.js v21.7.1 CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  node5-js-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.7.1]  # Specific Node.js version

    steps:
      - name: 🔄 Checkout Repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: 📦 Install Dependencies
        run: npm ci

      - name: 🛠️ Build Project
        run: npm run build

      - name: ✅ Run Tests
        run: npm test
